# Generated by Django 5.1.5 on 2025-01-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
